# Generated by Django 5.0.6 on 2026-06-17 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotarizationRecord',
            fields=[
                ('record_id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('document_hash', models.CharField(max_length=64)),
                ('txid', models.CharField(max_length=64)),
                ('signature', models.TextField(blank=True, default='')),
                ('public_key', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='notarized_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryLink',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_links', to='records.notarizationrecord')),
            ],
        ),
    ]
