# Generated by Django 5.0.6 on 2026-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publickeys', '0002_userpublickey_delete_publickey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpublickey',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userpublickey',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpublickey',
            name='verified',
        ),
        migrations.AlterField(
            model_name='userpublickey',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userpublickey',
            name='public_key',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='userpublickey',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
    ]
