# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publickeys', '0003_remove_userpublickey_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublickey',
            name='label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
